version: '2'
services:
    crawlerscheduler-app:
        image: crawlerscheduler
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${simlife.registry.password}@simlife-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${simlife.registry.password}@simlife-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://crawlerscheduler-mysql:3306/crawlerscheduler?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SIMLIFE_SLEEP=30 # gives time for the Simlife Registry to boot before the application
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    crawlerscheduler-mysql:
        extends:
            file: mysql.yml
            service: crawlerscheduler-mysql
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
    simlife-registry:
        extends:
            file: simlife-registry.yml
            service: simlife-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
